//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerEntity
    {
        public System.Guid AnswerID { get; set; }
        public string AnswerTitle { get; set; }
        public string Description { get; set; }
        public string File { get; set; }
        public System.DateTime CreateDate { get; set; }
        public float Mark { get; set; }
        public int Status { get; set; }
        public string StudentID { get; set; }
        public System.Guid TestID { get; set; }
    
        public virtual PersonEntity Person { get; set; }
        public virtual TestEntity Test { get; set; }
    }
}
