//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassStudentEntity
    {
        public System.Guid ID { get; set; }
        public System.Guid ClassID { get; set; }
        public string StudentID { get; set; }
    
        public virtual ClassEntity Class { get; set; }
        public virtual PersonEntity Person { get; set; }
    }
}
