//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentManagementDBContext : DbContext
    {
        public StudentManagementDBContext()
            : base("name=StudentManagementDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerEntity> AnswerEntities { get; set; }
        public virtual DbSet<ClassEntity> ClassEntities { get; set; }
        public virtual DbSet<PersonEntity> PersonEntities { get; set; }
        public virtual DbSet<TestEntity> TestEntities { get; set; }
    }
}
